//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomataEntitiesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Assemblies = new HashSet<Assembly>();
            this.Projects = new HashSet<Project>();
        }
    
        public int PK_Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string SecretAnswer { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Assembly> Assemblies { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
