//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automata.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        public Parameter()
        {
            this.TestParameters = new HashSet<TestParameter>();
        }
    
        public int PK_Id { get; set; }
        public int Position { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
    
        public virtual ParameterType ParameterType { get; set; }
        public virtual Procedure Procedure { get; set; }
        public virtual ICollection<TestParameter> TestParameters { get; set; }
    }
}
